image: docker:latest

variables:
  DOCKER_DRIVER: overlay

before_script:
- docker info

build:
  only:
  - master6
  stage: build
  script:
  - docker build -t armiax2/apps .
  - docker login -u armiax2 -p $CI_GITHUB_PASSWORD
  - docker push armiax2/apps

